#feign:
#  compression:
#    request:
#      ebabled: true
#      mime-types: text/xml,application/xml,application/json
#      min-request-size: 2048
#    response:
#      enabled: true
#
server:
  port: 8083

feign:
  hystrix:
    enabled: true